### ISSUE TITLE
How to use this approach for new dataset?

### ISSUE THREAD

**Issue by jeannie14** [elieJalbout/Clustering-with-Deep-learning#7]
Can we use trained auto-encoder using your approach for clustering custom dataset (other than MNIST and COIL)?

**Comment by ElieAljalbout** [comment]
If the auto-encoder is trained on MNIST or COIL, then the learned representation mapping is clustering friendly with respect to the input space of the dataset you used, in case the new dataset you want to cluster is somehow similar, then you can use the network as is, otherwise you would have to re-train with your new data (which is also easy because the method is fully unsupervised)
